### ISSUE TITLE
When I run the script nothing happens (Windows 11)

### ISSUE THREAD

**Issue by stiansci** [alb3rtov/lid-screen-suspender#1]
I also tried to manually run the script in Power Shell but I get a blank command line.
<img width="211" alt="Immagine 2022-08-31 120300" src="https://user-images.githubusercontent.com/40665124/187653539-8a525a9c-b560-46b6-9d9c-1e7ac634377f.png">

**Comment by alb3rtov** [comment]
I commit a change in the code in order to set a initial configuration for the behavior of the screen lid. I test it in Windows 10 and it works, but a I can't test it correctly in Windows 11 because in virtual machines doesn't appear the screen lid behavior menu.

The script does not print anything, so there is no output lines, just make sure that in your screen lid behavior menu changes the following options while the script is running:

![image](https://user-images.githubusercontent.com/40604222/187666302-88d75821-89d5-4515-bcce-059725c592e4.png)

If not, make sure you have configure `Balanced` in the power plan settings:

![image](https://user-images.githubusercontent.com/40604222/187666896-41b2bf3e-9619-45f0-8bfc-60c7176545ff.png)

**Comment by stiansci** [comment]
Thanks for the detailed answer
